require: rubocop-rspec
plugins:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  DisabledByDefault: true
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'

# Layout
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['\A\s*#']

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# Metrics
Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/ClassLength:
  Max: 400

Metrics/ModuleLength:
  Max: 200

Metrics/BlockLength:
  Max: 30
  AllowedMethods: ['describe', 'context', 'it', 'specify']
  Exclude:
    - 'spec/**/*'

# Performance
Performance/StringReplacement:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

# RSpec specific
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Enabled: true

RSpec/FilePath:
  Enabled: true

RSpec/SpecFilePathFormat:
  Enabled: true
